# Generated by Django 3.2.5 on 2021-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
